apiVersion: batch/v1
kind: CronJob
metadata:
  name: "2022"
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "2022"
              image: ${IMAGE}
              imagePullPolicy: IfNotPresent
              env:
                - name: DATABASE_URL
                  value: ${DATABASE_URL}
                - name: GITHUB_OWNER
                  value: ${GITHUB_OWNER}
                - name: GITHUB_REPOSITORY
                  value: ${GITHUB_REPOSITORY}
                - name: SLACK_TOKEN
                  value: ${SLACK_TOKEN}
                - name: SLACK_CHANNEL_ID
                  value: ${SLACK_CHANNEL_ID}
          restartPolicy: Never
